#!/bin/sh

curl localhost:2000/mine
curl localhost:2000/mine
curl localhost:2000/mine
curl "localhost:5000/add_peer" -H "Content-Type: application/json" -d '{"url" : "http://localhost:2000"}'
curl localhost:5000/sync
